name: 'tagged-release'

on:
  push:
    

jobs:
  gh_tagged_release:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          lfs: true
          fetch-depth: 0

      
      - uses: ok-nick/setup-aftman@v0.4.2
      - run: "aftman install"
      - run: "rojo build -o module.rbxm"

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          title: "release"
          files: |
            LICENSE.md
            module.rbxm